[project]
name = "fraud-prevention"
version = "1.0"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
pythonpath = "." 
addopts = ["--import-mode=importlib",]